### ISSUE TITLE
Python3 exec exception during decryption 

### ISSUE THREAD

**Issue by regpa** [fcoiffie/decode-ColorNote#1]
Hello,

I tried:
`$python3 decode-ColorNote.py ./colornote/`
 
with only one single .doc file in the colornote folder and I got:
`Traceback (most recent call last):
  File "decode-ColorNote.py", line 156, in <module>
    main()
  File "decode-ColorNote.py", line 143, in main
    json_chunk = json.loads(chunk.decode("utf-8"))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 1: invalid start byte`

I would need some details on the .doc file data structure to work on a fix and contribute.
could you please give some hint on where to start from ?

I thank in advance

**Comment by fcoiffie** [comment]
Hi,
You can check if the .doc was correctly deciphered: it remains my debug code which creates a `/tmp/notes.bin` file. You can open this file with a text editor: it mainly contains JSON (with length coded as binary at the beginning).
Maybe, your JSON doesn't content utf-8 or there is an other kind of content (that I haven't in my own notes)

**Comment by regpa** [comment]
Hi
thanks for your quick answer, indeed I was wrongly writing the command line. I looking more detail in your code I have better understood the -p option, with:
`$python3 decode-ColorNote.py  -p xxxx  ./colornote/`
it worked like a charm!
your code is quite clear, It deserves more notoriety
